services:
  api:
    build:
      context: ./docker/
      dockerfile: go-air.Dockerfile
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    networks:
      - memo-app-network
  mongo:
    image: mongo:8.0.8-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - memo-app-network-vol-db:/data/db

    networks:
      - memo-app-network
  nodered:
    image: nodered/node-red
    ports:
      - 1880:1880
    networks:
      - memo-app-network
    volumes:
      - memo-app-network-vol-nr:/data
    environment:
      - TZ=Asia/Bangkok
networks:
  memo-app-network:
    driver: bridge
volumes:
  memo-app-network-vol-db:
    driver: local
  memo-app-network-vol-nr:
    driver: local
